version: "3.9"

services:
  backend:
    build: ./backend
    container_name: simple-backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DB_USER=sa
      - DB_PASSWORD=YourStrong!Passw0rd
      - DB_SERVER=db
      - DB_NAME=SimpleAppDB
    volumes:
      - ./backend:/usr/src/app
    networks:
      - simple-net

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong!Passw0rd
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - simple-net

networks:
  simple-net:
    driver: bridge